import type { TeachingNotes } from "./teaching";

type NoteEntries = Record<number, readonly [title: string, explanation: string]>;

function notes(entries: NoteEntries): TeachingNotes {
  return Object.fromEntries(
    Object.entries(entries).map(([line, [title, explanation]]) => [
      Number(line),
      { explanation, title },
    ]),
  );
}

export const teachingNotesByExample: Record<string, TeachingNotes> = {
  "cfg-reverse-postorder": notes({
    3: ["Define the traversal", "This function will turn a reachable CFG into an order suited to forward data-flow analysis."],
    4: ["Track visited blocks", "The visited set prevents loop back-edges from recursively revisiting the same basic block."],
    5: ["Collect postorder", "Blocks enter this list only after their reachable successors have been explored."],
    7: ["Define recursive DFS", "The nested visitor explores one basic block and all successors reachable from it."],
    8: ["Mark this block visited", "Marking before following edges makes cycles in the CFG terminate safely."],
    10: ["Inspect each successor", "Every outgoing control-flow edge must be traversed to cover the reachable graph."],
    11: ["Skip known successors", "Only unseen successors need recursion; visited ones are back-edges or joins already handled."],
    12: ["Descend through the CFG", "Recursion finishes the successor before adding the current block to postorder."],
    16: ["Finish this block", "Appending after all successors gives this block its postorder position."],
    19: ["Start at the entry", "CFG analyses operate on blocks reachable from the function entry."],
    20: ["Create the final order", "A separate array receives the reversal without mutating the traversal result."],
    22: ["Reverse postorder", "Walking postorder backward tends to place a block before the blocks it can reach."],
    23: ["Append the next block", "This copies the current postorder element into its reverse-postorder position."],
    26: ["Return the block order", "The resulting order is ready for a forward compiler analysis worklist."],
    29: ["Define a loop CFG", "This example graph contains a loop back-edge from body to header."],
    36: ["Run the ordering pass", "The output demonstrates the order produced for the sample loop CFG."],
  }),
  "iterative-dominators": notes({
    4: ["Define set intersection", "Dominator equations intersect the dominator sets of every CFG predecessor."],
    5: ["Create the intersection", "This result will contain only blocks present in both incoming dominator sets."],
    7: ["Check each candidate", "Every block dominating the left predecessor is tested against the right predecessor."],
    8: ["Keep common dominators", "A block survives only when it dominates both predecessor paths."],
    9: ["Record the common block", "This adds a confirmed shared dominator to the intersection."],
    13: ["Return the intersection", "The caller uses this set while combining additional predecessor paths."],
    16: ["Define dominator analysis", "This fixed-point solver computes which blocks dominate every CFG block."],
    21: ["Store dominator sets", "Each CFG block maps to the set of blocks currently believed to dominate it."],
    22: ["Build the universal set", "Non-entry blocks begin conservatively with every block as a possible dominator."],
    24: ["Enumerate CFG blocks", "The universal initial set must contain every block in the function."],
    25: ["Add a possible dominator", "This grows the initial top value used by the iterative data-flow analysis."],
    28: ["Initialize each equation", "The entry has only itself; every other block starts with the universal set."],
    29: ["Seed dominator information", "These boundary values let later iterations monotonically remove impossible dominators."],
    32: ["Request the first pass", "At least one analysis pass is required before the sets can be considered stable."],
    34: ["Iterate to a fixed point", "The equations repeat until an entire pass produces no dominator-set changes."],
    35: ["Assume stability", "Any update in this pass will set changed back to true and request another pass."],
    37: ["Recompute each block", "Every non-entry block applies the dominator transfer equation."],
    38: ["Preserve the boundary", "The entry dominator set is fixed and must not be recomputed from predecessors."],
    39: ["Skip the entry", "Control moves to the next block because the entry has no incoming CFG paths."],
    42: ["Read incoming paths", "A block is dominated only by blocks common to all of these predecessors."],
    43: ["Seed the intersection", "The first predecessor provides the initial set before remaining sets are intersected."],
    45: ["Combine predecessors", "Each additional incoming path can remove candidates that do not dominate that path."],
    46: ["Narrow the set", "This retains only dominators shared with the current predecessor."],
    49: ["Add the block itself", "Every block dominates itself, regardless of its predecessors."],
    51: ["Detect a changed solution", "A different set size means this block lost or gained dominator information."],
    52: ["Commit the new set", "The refined dominators become available to later blocks and later passes."],
    53: ["Schedule another pass", "Downstream equations may change because this block's result changed."],
    58: ["Return the fixed point", "All dominator equations are now stable for the sample CFG."],
    61: ["List analysis blocks", "This defines the universe and deterministic processing order for the solver."],
    62: ["Define CFG predecessors", "Dominator information flows into a block from each incoming edge."],
    66: ["Run dominator analysis", "The printed sets show which blocks occur on every entry-to-block path."],
  }),
  "dominance-frontiers": notes({
    3: ["Define frontier construction", "This pass finds join points where a block's strict dominance ends."],
    8: ["Create frontier sets", "Each block receives the CFG joins in its dominance frontier."],
    10: ["Initialize every block", "An empty list is required before joins contribute frontier members."],
    11: ["Start with no frontier", "The analysis will add only joins proven by incoming paths."],
    14: ["Inspect possible joins", "Only blocks with multiple predecessors can merge distinct control-flow paths."],
    15: ["Require a real join", "A block with fewer than two predecessors cannot create a dominance frontier here."],
    16: ["Skip non-joins", "No frontier propagation is needed for a single-entry block."],
    19: ["Follow each incoming path", "Each predecessor contributes blocks whose dominance ends at this join."],
    20: ["Start from the predecessor", "The runner walks upward through immediate dominators toward the join's dominator."],
    22: ["Climb to the common dominator", "Every runner before the join's immediate dominator has this join in its frontier."],
    23: ["Avoid duplicate joins", "Multiple incoming paths may try to add the same frontier member."],
    24: ["Add the frontier member", "This join is reachable from the runner without the runner strictly dominating it."],
    26: ["Move up the dominator tree", "The immediate dominator continues propagation toward the common ancestor."],
    31: ["Return all frontiers", "These sets can now drive Cytron phi-function placement."],
    34: ["List CFG blocks", "The example uses a diamond-shaped graph with one join."],
    35: ["Define incoming edges", "The join has left and right predecessors, creating a frontier."],
    39: ["Provide immediate dominators", "The dominator tree determines how far each predecessor runner climbs."],
    43: ["Compute the frontiers", "The result identifies join as a frontier member of both branches."],
  }),
  "cytron-phi-placement": notes({
    3: ["Define Cytron placement", "This worklist algorithm computes phi locations from variable definitions and dominance frontiers."],
    8: ["Store phi functions", "Each CFG block maps to the variables requiring a phi function there."],
    10: ["Process one variable", "Phi placement is computed independently for each source variable."],
    11: ["Seed with definitions", "Every block assigning this variable starts the iterated-dominance-frontier worklist."],
    12: ["Track queued blocks", "This prevents a block from being added to the worklist repeatedly."],
    14: ["Mark definition blocks", "Initial definition sites are already represented in the worklist."],
    15: ["Remember the queued site", "Later phi insertion will not requeue an original definition block."],
    18: ["Expand the iterated frontier", "Processing continues until newly placed phi definitions add no new frontier blocks."],
    19: ["Take the next definition site", "The block may contain an original assignment or a newly inserted phi definition."],
    21: ["Guard an empty queue", "The shift result is checked before it is used as a CFG block key."],
    25: ["Inspect frontier joins", "Each frontier block is a point where competing definitions can meet."],
    26: ["Initialize the join", "The first phi assigned to this block needs a variable list."],
    27: ["Create the phi list", "This block is now prepared to hold one or more phi functions."],
    30: ["Avoid duplicate phi functions", "A block needs at most one phi function for a particular variable."],
    31: ["Place the phi function", "The join now merges the reaching versions of this variable."],
    33: ["Treat phi as a definition", "A new phi definition may itself require phis in further dominance frontiers."],
    34: ["Mark the join queued", "Recording it first prevents cyclic frontiers from scheduling it indefinitely."],
    35: ["Continue iterated placement", "The new definition site is added so its own frontier will be processed."],
    42: ["Return phi locations", "The result is the minimal placement produced by iterated dominance frontiers."],
    45: ["Choose SSA variables", "The example computes phi placement for x and y independently."],
    46: ["Define assignment sites", "These are the CFG blocks where each variable receives a value."],
    50: ["Provide dominance frontiers", "These precomputed joins tell Cytron's algorithm where definitions can converge."],
    54: ["Run phi placement", "The output shows which variables require phi functions at each join."],
  }),
  "ssa-renaming": notes({
    4: ["Define SSA renaming", "This dominator-tree traversal gives each definition a unique version and rewrites its uses."],
    11: ["Track local definitions", "Variables pushed in this block must be popped when traversal leaves the block."],
    13: ["Visit block statements", "Statements are renamed in program order so each use sees the latest dominating definition."],
    14: ["Read statement kind", "The algorithm handles uses differently from definitions."],
    15: ["Read the base variable", "The unversioned name selects the correct counter and version stack."],
    17: ["Handle a use", "A use must refer to the most recent definition dominating this block."],
    18: ["Read available versions", "The stack contains active definitions along the current dominator-tree path."],
    19: ["Rewrite the use", "The top stack entry is the nearest dominating SSA version."],
    20: ["Handle a definition", "A definition creates a new SSA name instead of reusing the source variable."],
    21: ["Allocate a version number", "Incrementing the counter makes this definition globally unique."],
    22: ["Build the SSA name", "Combining the variable and counter produces a name such as x1 or x2."],
    23: ["Expose the definition", "Pushing makes this version available to dominated uses."],
    24: ["Rename the definition", "The statement now defines its unique SSA version."],
    25: ["Remember the stack change", "This records which variable stack must be restored after the subtree."],
    29: ["Visit dominated blocks", "Children inherit all definitions currently active on the stacks."],
    30: ["Recurse down the tree", "The child is renamed while this block's definitions remain visible."],
    33: ["Restore the incoming state", "Leaving the block removes definitions that must not reach sibling subtrees."],
    34: ["Pop the local version", "The previous dominating definition becomes visible again."],
    38: ["Define sample statements", "The simplified IR distinguishes variable definitions from uses across four blocks."],
    44: ["Define the dominator tree", "This tree controls which definitions are visible during renaming."],
    47: ["Run SSA renaming", "Counters start at zero and stacks start empty before the entry definition is processed."],
    48: ["Inspect the SSA form", "The output shows distinct versions on definitions and their corresponding uses."],
  }),
  "linear-search": {
    1: {
      title: "What linear search does",
      explanation:
        "This function looks through a list for one number, called the **target**. It checks items from left to right. If it finds the target, it returns that item's **index**. If the target is not in the list, it returns `-1`.",
      arguments: {
        values: "The list of numbers to search, starting from the left.",
        target: "The number we want to find.",
      },
    },
    2: {
      title: "Look at one index at a time",
      explanation:
        "Start at index `0`, the first item. After each check, move one step right with `index += 1`. Stop when `index` reaches `values.length`, because that means every item has already been checked.",
    },
    3: {
      title: "Ask: is this the target?",
      explanation:
        "Read the number at this index and compare it with the target. If they are equal, we found it. If not, this item is not the answer, so the loop will try the next index.\n\nIn this lesson the list is `[8, 3, 11, 6, 2]`. The first search looks for `6`; the second looks for `4`.",
      question: "If this number equals the target, what should the function do?",
      choices: [
        "Stop searching and return this index.",
        "Keep scanning to see if the number appears again later.",
        "Sort the list and start a binary search.",
      ],
      answer: 0,
      solution:
        "A match means we have found the target. Linear search returns that index immediately and does not look at the rest of the list.",
    },
    4: {
      title: "Return where it was found",
      explanation:
        "The answer is the **index**, not the number itself. The caller already knows the target value; they need its position. Finding `6` at index `3` means `values[3]` is `6`.",
      question: "Why return `index` instead of `target`?",
      choices: [
        "The caller already knows the target. The useful result is where it sits in the list.",
        "The index is always smaller, so it is faster to return.",
        "Returning the target proves the search sorted the list.",
      ],
      answer: 0,
      solution:
        "The target is the input we already had. The new information is its position, so the function returns the index.",
    },
    8: {
      title: "Report that it was not found",
      explanation:
        "If the loop finishes, every item was checked and none matched. `-1` means \"not in the list\". We cannot return `0` for a miss, because `0` already means \"found at the first item\". The second search looks for `4`, which is missing, so this line runs.",
      question: "Why return `-1` instead of `0` when the target is missing?",
      choices: [
        "`0` already means \"found at the first item\", so `-1` is reserved for \"not found\".",
        "Negative numbers search faster than zero.",
        "`-1` sorts the list into reverse order.",
      ],
      answer: 0,
      solution:
        "Index `0` is a real position. Returning `0` for a miss would look like a successful find at the start. `-1` cannot be a valid index, so it clearly means \"not found\".",
    },
    11: {
      title: "Make a small example list",
      explanation:
        "These five numbers are intentionally out of order. That is why we cannot jump to the middle. We have to check them in order: `8`, then `3`, then `11`, then `6`, then `2`.",
    },
    12: {
      title: "First search: a number that is in the list",
      explanation:
        "Find `6` in the list. The search will skip `8`, `3`, and `11`, then match `6` at index `3` and stop. Watch the `index` variable as you step.",
    },
    13: {
      title: "Second search: a number that is missing",
      explanation:
        "Now search for `4`, which is not in the list. This time the loop checks every item and then returns `-1`. Comparing the two searches shows both outcomes of linear search.",
    },
    14: {
      title: "Print the successful result",
      explanation:
        "This should print `3`, because `6` is the fourth number in the list. Indexes start at `0`, so the fourth item is index `3`.",
    },
    15: {
      title: "Print the missing result",
      explanation:
        "This should print `-1`, confirming that `4` was not in the list.",
    },
  },
  "binary-search": notes({
    1: ["Define binary search", "This function exploits sorted order to discard half the remaining range each iteration."],
    2: ["Set the lower bound", "The candidate search interval initially begins at the first array index."],
    3: ["Set the upper bound", "The candidate interval initially ends at the final array index."],
    5: ["Check for remaining candidates", "The search continues while the lower bound has not crossed the upper bound."],
    6: ["Choose the midpoint", "Testing the middle element divides the remaining sorted range into two halves."],
    7: ["Read the middle value", "This value determines whether the target is found, lower, or higher."],
    9: ["Test for a match", "Equality means the midpoint is the target's index."],
    10: ["Return the midpoint", "The search terminates as soon as the target is found."],
    13: ["Choose the surviving half", "Sorted order tells the algorithm which side of the midpoint can contain the target."],
    14: ["Discard the lower half", "A larger target must occur strictly to the right of the midpoint."],
    15: ["Handle a smaller target", "If the target is not larger, only the left half can still contain it."],
    16: ["Discard the upper half", "A smaller target must occur strictly to the left of the midpoint."],
    23: ["Create sorted input", "Binary search requires ascending values for its half-discarding decisions to be valid."],
    24: ["Search for 16", "The example invokes binary search and stores the discovered index."],
    25: ["Report the result", "This confirms that the midpoint reductions located the target."],
  }),
  "bubble-sort": notes({
    1: ["Define bubble sort", "This function repeatedly swaps inverted adjacent pairs until the array is ordered."],
    2: ["Copy the input", "Sorting a clone preserves the caller's original array."],
    4: ["Shrink the unsorted suffix", "Each completed pass moves its largest remaining value to end, so that position is finished."],
    5: ["Compare adjacent positions", "The inner pass examines every neighboring pair before the sorted suffix."],
    6: ["Detect an inversion", "A larger left value must move right to restore ascending order."],
    7: ["Save the left value", "Temporary storage prevents the first assignment from losing a value during the swap."],
    8: ["Move the smaller value left", "This removes the adjacent inversion."],
    9: ["Move the larger value right", "Completing the swap bubbles the larger value toward the sorted suffix."],
    14: ["Return the sorted copy", "All passes are complete, so every adjacent pair is in ascending order."],
    17: ["Sort sample values", "The unsorted input exercises several adjacent swaps."],
    18: ["Report the ordering", "This displays the array after all bubble-sort passes."],
  }),
  "insertion-sort": notes({
    1: ["Define insertion sort", "This function grows a sorted prefix by inserting one value at a time."],
    2: ["Copy the input", "The algorithm rearranges a clone rather than mutating the caller's array."],
    4: ["Select the next value", "Index zero is already a sorted prefix; each later value is inserted into that prefix."],
    5: ["Hold the value to insert", "Saving it allows larger prefix values to shift right without overwriting it."],
    6: ["Start left of the gap", "This position tracks values in the sorted prefix that may need shifting."],
    8: ["Find the insertion point", "Larger prefix values move right until the correct position for current is exposed."],
    9: ["Shift a larger value", "Moving this value right opens a gap one position further left."],
    10: ["Continue moving left", "The next earlier prefix value is checked against the value being inserted."],
    13: ["Insert the saved value", "The remaining gap is the first position where sorted order is preserved."],
    16: ["Return the sorted copy", "Every input element has now been inserted into the sorted prefix."],
    19: ["Sort sample values", "This input demonstrates both short and multi-position insertions."],
    20: ["Report the ordering", "This displays the array after the prefix has grown across all values."],
  }),
  "selection-sort": notes({
    1: ["Define selection sort", "This function repeatedly selects the smallest value remaining in the unsorted suffix."],
    2: ["Copy the input", "The sort rearranges a clone and leaves the original array unchanged."],
    4: ["Choose the next output position", "Everything before start is already final and sorted."],
    5: ["Assume the first candidate", "The suffix begins by treating its first value as the smallest seen."],
    7: ["Scan the remaining suffix", "Every later value must be checked because the suffix is unsorted."],
    8: ["Compare with the current minimum", "A smaller candidate should replace the selected index."],
    9: ["Remember the new minimum", "The eventual swap will move this value into the current output position."],
    13: ["Save the start value", "Temporary storage keeps it available while the selected minimum moves left."],
    14: ["Place the minimum", "The smallest suffix value is moved into its final sorted position."],
    15: ["Complete the swap", "The displaced start value fills the minimum's previous position."],
    18: ["Return the sorted copy", "Every position except the final implied maximum has been selected."],
    21: ["Sort sample values", "The example selects successive minimum values from this input."],
    22: ["Report the ordering", "This displays the final result of the selection passes."],
  }),
  "merge-sort": notes({
    1: ["Define the merge step", "This function combines two already sorted arrays into one sorted result."],
    2: ["Create merged output", "Values are appended here in ascending order."],
    3: ["Track the left candidate", "This index points to the smallest unmerged value in the left half."],
    4: ["Track the right candidate", "This index points to the smallest unmerged value in the right half."],
    6: ["Compare while both halves remain", "The smaller front value across the two halves must be next in the output."],
    7: ["Choose the left candidate", "Using less-than-or-equal preserves stable ordering for equal values."],
    8: ["Append from the left", "The selected left value is the smallest value not yet merged."],
    9: ["Advance the left index", "The next left value becomes that half's candidate."],
    10: ["Choose the right candidate", "The right front value is smaller and therefore belongs next."],
    11: ["Append from the right", "The selected right value is the smallest value not yet merged."],
    12: ["Advance the right index", "The next right value becomes that half's candidate."],
    16: ["Drain the left remainder", "Once the right half is empty, remaining left values are already ordered."],
    17: ["Append a remaining left value", "No right-side candidate remains to compare against it."],
    18: ["Advance through the left remainder", "This moves toward exhausting the left half."],
    21: ["Drain the right remainder", "Once the left half is empty, remaining right values are already ordered."],
    22: ["Append a remaining right value", "No left-side candidate remains to compare against it."],
    23: ["Advance through the right remainder", "This moves toward exhausting the right half."],
    26: ["Return the merged array", "Both sorted halves have been combined without inversions."],
    29: ["Define recursive merge sort", "This function divides the input until trivial arrays can be merged back together."],
    30: ["Check the base case", "An empty or single-value array is already sorted and stops recursion."],
    31: ["Return the trivial array", "No division or merge work is needed at this recursion leaf."],
    34: ["Find the split point", "The midpoint divides the problem into two roughly equal subproblems."],
    35: ["Sort the left half", "Recursion produces a sorted left input for the merge step."],
    36: ["Sort the right half", "Recursion produces a sorted right input for the merge step."],
    37: ["Merge the sorted halves", "Combining the two recursive results creates the sorted result for this call."],
    40: ["Sort sample values", "The example starts the divide-and-merge recursion."],
    41: ["Report the ordering", "This displays the result after all recursive merges complete."],
  }),
  "quick-sort": notes({
    1: ["Define a swap", "Partitioning uses this helper to exchange two array positions in place."],
    2: ["Save the left value", "Temporary storage prevents it from being overwritten during the exchange."],
    3: ["Move the right value left", "The right-side value takes the left position."],
    4: ["Complete the exchange", "The saved left value moves into the right position."],
    7: ["Define partitioning", "This function groups values below the pivot before values at least as large."],
    8: ["Choose the pivot", "The final value is used as the comparison point for this partition."],
    9: ["Start the lower partition", "Boundary marks the next slot reserved for a value smaller than the pivot."],
    11: ["Scan non-pivot values", "Every value in the range is classified relative to the pivot."],
    12: ["Find a lower value", "Values below the pivot belong before the current boundary."],
    13: ["Move it into the lower partition", "The swap extends the group of values smaller than the pivot."],
    14: ["Advance the boundary", "The next lower value should occupy the following position."],
    18: ["Place the pivot", "Moving the pivot to boundary puts it between the lower and upper partitions."],
    19: ["Return the pivot position", "This final index splits the two recursive quick-sort ranges."],
    22: ["Define recursive quick sort", "This function partitions a range and recursively sorts the two sides."],
    23: ["Check for a trivial range", "A range with zero or one value is already sorted."],
    24: ["Stop this recursion branch", "No partition is needed when low has reached or crossed high."],
    27: ["Partition the range", "The pivot is placed permanently and its final index is returned."],
    28: ["Sort below the pivot", "Only values strictly left of the pivot remain unsorted in this subproblem."],
    29: ["Sort above the pivot", "Only values strictly right of the pivot remain unsorted in this subproblem."],
    32: ["Create mutable input", "Quick sort rearranges this sample array in place."],
    33: ["Sort the full range", "The initial recursion covers every index in the array."],
    34: ["Report the ordering", "This displays the array after all partitions finish."],
  }),
  "breadth-first-search": notes({
    3: ["Define breadth-first search", "This traversal visits graph vertices in increasing distance from the start."],
    4: ["Seed the queue", "The start vertex forms level zero of the breadth-first traversal."],
    5: ["Track discovered vertices", "This prevents cycles and converging edges from enqueuing a vertex repeatedly."],
    6: ["Record visit order", "Dequeued vertices are appended here to expose the level-order traversal."],
    7: ["Discover the start", "Marking at enqueue time ensures no neighbor can enqueue the start again."],
    9: ["Process the frontier", "The queue contains discovered vertices whose outgoing edges still need inspection."],
    10: ["Take the oldest vertex", "FIFO removal is what makes breadth-first search proceed level by level."],
    12: ["Guard the queue result", "The runtime type allows undefined, although the loop condition normally prevents it."],
    16: ["Visit this vertex", "The oldest frontier vertex now becomes the next traversal result."],
    17: ["Read outgoing neighbors", "These vertices are one edge farther from the start."],
    19: ["Inspect each edge", "Every outgoing edge may reveal an undiscovered vertex."],
    20: ["Check discovery state", "Only the first path to a vertex should enqueue it."],
    21: ["Mark the neighbor discovered", "Doing this before enqueueing prevents duplicate queue entries."],
    22: ["Extend the BFS frontier", "The neighbor waits behind all vertices already discovered at the same or earlier level."],
    27: ["Return level order", "The queue discipline has produced vertices by their shortest unweighted distance."],
    30: ["Define the sample graph", "The adjacency lists contain branching and a shared vertex F."],
    39: ["Start from A", "The traversal explores only the component reachable from A."],
    40: ["Report visit order", "This reveals the breadth-first level ordering."],
  }),
  "depth-first-search": notes({
    3: ["Define depth-first search", "This traversal follows one graph branch completely before backtracking."],
    9: ["Mark the current vertex", "Recording discovery prevents cycles from causing infinite recursion."],
    10: ["Visit the vertex", "The vertex enters the result as soon as recursion first reaches it."],
    12: ["Inspect outgoing edges", "Each neighbor may begin a deeper recursive branch."],
    13: ["Skip discovered vertices", "Only unseen neighbors need traversal, avoiding cycles and duplicate visits."],
    14: ["Descend into the neighbor", "Recursion explores this entire branch before continuing the current neighbor loop."],
    19: ["Define the sample graph", "The adjacency lists include branches and a shared destination."],
    27: ["Create the visited set", "No vertices are discovered before traversal starts at A."],
    28: ["Create the result order", "First visits will be appended as recursion explores the graph."],
    29: ["Start from A", "Only vertices reachable from the selected root are traversed."],
    30: ["Report visit order", "This shows the branch-first order produced by recursive DFS."],
  }),
  "dijkstra-shortest-path": notes({
    3: ["Define Dijkstra's algorithm", "This function computes minimum path costs from one source in a non-negative weighted graph."],
    4: ["Store best-known costs", "Each vertex maps to the cheapest source path discovered so far."],
    5: ["Track finalized vertices", "A finalized vertex already has its optimal distance and need not be selected again."],
    7: ["Initialize every vertex", "Before any path is known, each distance begins at infinity."],
    8: ["Mark distance unknown", "Infinity allows any real discovered path to improve this vertex."],
    10: ["Seed the source", "The path from the start vertex to itself has cost zero."],
    12: ["Select and relax repeatedly", "Each iteration finalizes one reachable vertex with the lowest tentative cost."],
    13: ["Reset the candidate", "No next vertex has been selected at the start of this iteration."],
    14: ["Reset the candidate cost", "Any finite unvisited distance can become the next minimum."],
    16: ["Scan unvisited vertices", "This simple implementation finds the minimum without a priority queue."],
    17: ["Find a cheaper candidate", "Only unvisited vertices with lower tentative distance can be selected next."],
    18: ["Select this vertex", "It is currently the closest unvisited vertex to the source."],
    19: ["Remember its cost", "Later candidates must beat this value to replace the selection."],
    23: ["Detect unreachable remainder", "No candidate means every reachable vertex has already been finalized."],
    24: ["Finish the search", "Remaining unvisited vertices have infinite distance and cannot be reached from the source."],
    27: ["Finalize the closest vertex", "With non-negative edges, no future route can improve this selected distance."],
    29: ["Relax outgoing edges", "Each neighbor may have a cheaper path through the newly finalized vertex."],
    30: ["Compute the alternative cost", "This extends the current shortest path by the edge to the neighbor."],
    32: ["Check for an improvement", "The distance changes only when this route is cheaper than the best known route."],
    33: ["Relax the neighbor", "The cheaper candidate becomes the neighbor's new tentative shortest distance."],
    38: ["Return shortest costs", "Every reachable vertex now has its optimal source distance."],
    41: ["Define a weighted graph", "All edge weights are non-negative, satisfying Dijkstra's requirement."],
    49: ["Compute paths from A", "A acts as the source whose distance is initialized to zero."],
    50: ["Report the distances", "The output shows the cheapest cost from A to each vertex."],
  }),
  "factorial-recursion": notes({
    1: ["Define recursive factorial", "This function expresses n factorial as n times the factorial of n minus one."],
    2: ["Check the base case", "Values zero and one terminate recursion with the multiplicative identity."],
    3: ["Return the identity", "Returning one lets the pending multiplication chain resolve correctly."],
    6: ["Reduce the problem", "This frame contributes value and delegates the smaller factorial to a recursive call."],
    9: ["Compute five factorial", "The call builds frames for 5, 4, 3, 2, and 1 before unwinding."],
    10: ["Report the product", "This displays the result accumulated while the recursive frames returned."],
  }),
  "fibonacci-dynamic-programming": notes({
    1: ["Define Fibonacci tabulation", "This function builds the sequence from previously computed values instead of repeating recursion."],
    2: ["Handle an empty request", "A non-positive count has no sequence elements to compute."],
    6: ["Seed F(0)", "Every later Fibonacci value ultimately depends on the initial zero."],
    8: ["Handle a one-value sequence", "When only F(0) is requested, the first seed is already the complete result."],
    12: ["Seed F(1)", "The second base value allows the recurrence to begin at index two."],
    14: ["Build remaining entries", "Each iteration computes exactly one new Fibonacci value."],
    15: ["Apply the recurrence", "The next value is the sum of the two immediately preceding tabulated results."],
    16: ["Store the subproblem result", "Appending makes this value available to the next iteration."],
    19: ["Return the table", "The array now contains the requested Fibonacci prefix with no repeated subproblems."],
    22: ["Generate ten values", "This invokes the iterative table-building process for a visible sequence."],
    23: ["Report the sequence", "This displays every computed dynamic-programming table entry."],
  }),
};
